permalink: /:year:month:day/:title
url: "https://firehomework.xyz" #Your url here
baseurl: "/win95-test"

# variables
name: Your Site Name
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]



 
# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
