permalink: /:year:month:day/:title
url: "https://firehomework.xyz" #Your url here
baseurl: "/win95-test"

# variables
name: Your Site Name
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes

 
# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
